/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as WishlistImport } from './routes/wishlist'
import { Route as StatusImport } from './routes/status'
import { Route as OriginalImport } from './routes/original'
import { Route as MaintenanceImport } from './routes/maintenance'
import { Route as IpoImport } from './routes/ipo'
import { Route as HantavirusImport } from './routes/hantavirus'
import { Route as DebugAuthImport } from './routes/debug-auth'
import { Route as AgiImport } from './routes/agi'
import { Route as AdminImport } from './routes/admin'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const WishlistRoute = WishlistImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRoute,
} as any)

const StatusRoute = StatusImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRoute,
} as any)

const OriginalRoute = OriginalImport.update({
  id: '/original',
  path: '/original',
  getParentRoute: () => rootRoute,
} as any)

const MaintenanceRoute = MaintenanceImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRoute,
} as any)

const IpoRoute = IpoImport.update({
  id: '/ipo',
  path: '/ipo',
  getParentRoute: () => rootRoute,
} as any)

const HantavirusRoute = HantavirusImport.update({
  id: '/hantavirus',
  path: '/hantavirus',
  getParentRoute: () => rootRoute,
} as any)

const DebugAuthRoute = DebugAuthImport.update({
  id: '/debug-auth',
  path: '/debug-auth',
  getParentRoute: () => rootRoute,
} as any)

const AgiRoute = AgiImport.update({
  id: '/agi',
  path: '/agi',
  getParentRoute: () => rootRoute,
} as any)

const AdminRoute = AdminImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminImport
      parentRoute: typeof rootRoute
    }
    '/agi': {
      id: '/agi'
      path: '/agi'
      fullPath: '/agi'
      preLoaderRoute: typeof AgiImport
      parentRoute: typeof rootRoute
    }
    '/debug-auth': {
      id: '/debug-auth'
      path: '/debug-auth'
      fullPath: '/debug-auth'
      preLoaderRoute: typeof DebugAuthImport
      parentRoute: typeof rootRoute
    }
    '/hantavirus': {
      id: '/hantavirus'
      path: '/hantavirus'
      fullPath: '/hantavirus'
      preLoaderRoute: typeof HantavirusImport
      parentRoute: typeof rootRoute
    }
    '/ipo': {
      id: '/ipo'
      path: '/ipo'
      fullPath: '/ipo'
      preLoaderRoute: typeof IpoImport
      parentRoute: typeof rootRoute
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceImport
      parentRoute: typeof rootRoute
    }
    '/original': {
      id: '/original'
      path: '/original'
      fullPath: '/original'
      preLoaderRoute: typeof OriginalImport
      parentRoute: typeof rootRoute
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusImport
      parentRoute: typeof rootRoute
    }
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agi': typeof AgiRoute
  '/debug-auth': typeof DebugAuthRoute
  '/hantavirus': typeof HantavirusRoute
  '/ipo': typeof IpoRoute
  '/maintenance': typeof MaintenanceRoute
  '/original': typeof OriginalRoute
  '/status': typeof StatusRoute
  '/wishlist': typeof WishlistRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agi': typeof AgiRoute
  '/debug-auth': typeof DebugAuthRoute
  '/hantavirus': typeof HantavirusRoute
  '/ipo': typeof IpoRoute
  '/maintenance': typeof MaintenanceRoute
  '/original': typeof OriginalRoute
  '/status': typeof StatusRoute
  '/wishlist': typeof WishlistRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agi': typeof AgiRoute
  '/debug-auth': typeof DebugAuthRoute
  '/hantavirus': typeof HantavirusRoute
  '/ipo': typeof IpoRoute
  '/maintenance': typeof MaintenanceRoute
  '/original': typeof OriginalRoute
  '/status': typeof StatusRoute
  '/wishlist': typeof WishlistRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/agi'
    | '/debug-auth'
    | '/hantavirus'
    | '/ipo'
    | '/maintenance'
    | '/original'
    | '/status'
    | '/wishlist'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/agi'
    | '/debug-auth'
    | '/hantavirus'
    | '/ipo'
    | '/maintenance'
    | '/original'
    | '/status'
    | '/wishlist'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/agi'
    | '/debug-auth'
    | '/hantavirus'
    | '/ipo'
    | '/maintenance'
    | '/original'
    | '/status'
    | '/wishlist'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AgiRoute: typeof AgiRoute
  DebugAuthRoute: typeof DebugAuthRoute
  HantavirusRoute: typeof HantavirusRoute
  IpoRoute: typeof IpoRoute
  MaintenanceRoute: typeof MaintenanceRoute
  OriginalRoute: typeof OriginalRoute
  StatusRoute: typeof StatusRoute
  WishlistRoute: typeof WishlistRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AgiRoute: AgiRoute,
  DebugAuthRoute: DebugAuthRoute,
  HantavirusRoute: HantavirusRoute,
  IpoRoute: IpoRoute,
  MaintenanceRoute: MaintenanceRoute,
  OriginalRoute: OriginalRoute,
  StatusRoute: StatusRoute,
  WishlistRoute: WishlistRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/admin",
        "/agi",
        "/debug-auth",
        "/hantavirus",
        "/ipo",
        "/maintenance",
        "/original",
        "/status",
        "/wishlist"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/admin": {
      "filePath": "admin.tsx"
    },
    "/agi": {
      "filePath": "agi.tsx"
    },
    "/debug-auth": {
      "filePath": "debug-auth.tsx"
    },
    "/hantavirus": {
      "filePath": "hantavirus.tsx"
    },
    "/ipo": {
      "filePath": "ipo.tsx"
    },
    "/maintenance": {
      "filePath": "maintenance.tsx"
    },
    "/original": {
      "filePath": "original.tsx"
    },
    "/status": {
      "filePath": "status.tsx"
    },
    "/wishlist": {
      "filePath": "wishlist.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
